### PR TITLE
Adding a Helm chart for deployment and improving hostname regex

### PR DESCRIPTION
**Pull request by rupertbenbrook**
Hope you don't mind, I found this project and it's exactly what I'm looking for as I have a home lab and my internal DNS is running on pihole.

I like deploying things with Helm, so I've created one using the existing deployment manifests as a start point. This has been validated in my home lab.

The existing regex to validate hostnames, both for the pihole host and ingress hosts, wouldn't allow longer domains like `one.two.three.org.uk`. This is valid, so I altered the regex to be more permissive, but still check RFC1123 hostnames.

### CODE REVIEW

**Comment by williamsanmartin4** [comment]
Good job 
I would open an issue with this incosistence

**Comment by rupertbenbrook** [comment]
@williamsanmartin4 good idea, have opened an issue and linked to this PR.

**Comment by tolson-vkn** [comment]
Hey sorry didn't see this. I'll review after work and merge thanks!

**Comment by tolson-vkn** [comment]
Busy night for me sorry. I am realizing I did some sill things in the provider code that I'm correcting and making the testing _actually work_. Also adding mutli arch images to the ghcr builds so. Slight change _tomorrow after work_ I'll merge it. :smiley:

**Comment by tolson-vkn** [comment]
Busy night for me sorry. I am realizing I did some sill things in the provider code that I'm correcting and making the testing _actually work_. Also adding mutli arch images to the ghcr builds so. Slight change _tomorrow after work_ I'll merge it. :smiley:

**Comment by tolson-vkn** [comment]
Ok thanks for this PR I am very a happy that this is useful for you and really appreciate the contributions. I'll get some new builds out.

Here's some context for my delays :sweat_smile: 
PXL_20220702_165253712

**Comment by tolson-vkn** [comment]
Gah I lost you as a contributor upon squashing. If you want credit on the repo page feel free to modify the readme or something of that sort and I'll try to correct that.

Hmm your commits show, maybe github will track you as a contributor later? Dunno but you're owed credit in my mind.

**Comment by rupertbenbrook** [comment]
Looks like a great place to code, so long as you've got power and internet! Don't worry about credit, just glad to contribute.

**Pull request merged**
